djangosolid/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("solid/", include("solidapp.urls")),
]

solidapp/urls.py
from django.urls import path
from . import views

app_name = "solidapp"

urlpatterns = [
    path("", views.index, name="index"),
    path("inspire", views.inspire, name="inspire"),
    path("getInspired", views.gotInspired, name="getInspired"),
    path("story/<int:id>/", views.story, name="story"),
]

solidapp/models.py
from django.db import models

# Create your models here.

solidapp/views.py
from django import forms
from django.shortcuts import render


class NewTaskForm(forms.Form):
    subscribtion = forms.CharField(label="Subscribe")


class NewStoryForm(forms.Form):
    title = forms.CharField(
        label="Title",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter title...",
            }
        ),
    )
    content = forms.CharField(
        label="Story",
        max_length=400,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Enter story...",
            }
        ),
    )


def index(request):
    return render(
        request,
        "solidapp/index.html",
        {
            "main": {
                "title": "Bridging the worlds of fans and creators, one story at a time.",
                "description": "Explore a digital library of creations inspired by real lives, and dive deeper into the art that speaks to you.",
            },
            "features": [
                {
                    "id": "01",
                    "title": "Inspire Your Favorite Artists",
                    "feature": "Let your story be a muse. Share your experiences, emotions, and dreams to inspire the creators you love. Every story has the potential to become part of something bigger.",
                },
                {
                    "id": "02",
                    "title": "Explore Online Galleries",
                    "feature": "Browse through virtual galleries showcasing art inspired by real stories. From illustrations to digital artwork, find the visuals that resonate with you and uncover the emotions behind them.",
                },
                {
                    "id": "03",
                    "title": "Audiobook Library",
                    "feature": "Immerse yourself in a growing library of audiobooks, each one crafted from stories that span the human experience. Enjoy these heartfelt narratives anytime, anywhere.",
                },
                {
                    "id": "04",
                    "title": "Translated Song Lyrics",
                    "feature": "Connect more deeply with your favorite music by exploring translated lyrics that capture the essence of songs inspired by fans. Language won’t be a barrier to feeling the music.",
                },
                {
                    "id": "05",
                    "title": "Exclusive Creator Updates",
                    "feature": "Stay updated with exclusive news from the artists you inspire. Get the latest on new projects, behind-the-scenes insights, and messages of appreciation straight from the creators.",
                },
                {
                    "id": "06",
                    "title": "Community for Art & Literature Lovers",
                    "feature": "Join a community that appreciates the fusion of personal stories with artistic expression. Share your thoughts, connect with other fans, and find friends who appreciate the power of words, art, and music.",
                },
            ],
            "about": {
                "title": "Where Stories Inspire Art",
                "description": "Welcome to Solid a place where art is inspired by you. Share your personal stories with your favorite artists—singers, writers, painters—and watch them turn your emotions into songs, visual art, and more. ",
            },
            "form": NewTaskForm(),
        },
    )


def inspire(request):
    return render(
        request,
        "solidapp/inspire.html",
        {
            "main": {
                "title": "Share Your Story, Inspire the Art",
                "description": "Welcome to our Story Submission page! This is your chance to make an impact on the creative world, and who knows? Your story might just be the spark behind the next masterpiece.",
            },
            "howItWorks": {
                "title": "Why Share Your Story?",
                "description": "Every artist seeks inspiration in the world around them. They strive to connect with stories, emotions, and real-life experiences to create art that resonates. Your story could be the one that ignites a powerful idea, a heartfelt song, a captivating painting, or an unforgettable piece of writing. Here’s why your story matters:",
                "steps": [
                    {
                        "id": "01",
                        "title": "Inspire Creativity",
                        "feature": "Artists need authentic, heartfelt stories to fuel their creativity. By sharing your story, you’re opening a door for them to explore new themes and ideas.",
                    },
                    {
                        "id": "02",
                        "title": "Leave a Legacy",
                        "feature": "Your story could be immortalized in a piece of art, capturing your unique perspective and emotions for the world to see.",
                    },
                    {
                        "id": "03",
                        "title": "Connect with Others",
                        "feature": "By sharing your experience, you’re joining a community of storytellers and art lovers, united by a love for creativity and expression.",
                    },
                ],
            },
            "form": NewStoryForm(),
        },
    )


def gotInspired(request):
    return render(
        request,
        "solidapp/get-inspired.html",
        {
            "main": {
                "title": "Inspiring Stories from Our Community",
                "description": "Welcome to our Story Gallery! Here, you’ll find a collection of heartfelt stories shared by people just like you. Each story offers a unique perspective, capturing moments of joy, resilience, love, and growth. These stories have been shared to inspire artists and art lovers, and we hope they’ll inspire you too",
                "section_title": "Explore Real Stories",
                "section_description": "Our community members have generously shared their personal journeys, memories, and dreams. Take your time to explore each story, let their words resonate, and feel the emotions and experiences that drive human creativity. Whether you're here to find inspiration or simply to connect, these stories are a testament to the beauty of shared experiences.",
            },
            "stories": {
                "title": "Featured Stories",
                "data": [
                    {
                        "id": 1,
                        "title": "The Dawn Within",
                        "content": "A journey of self-discovery, resilience, and finding hope in unexpected places. This story reminds us that even the darkest nights are followed by dawn.",
                        "date": "Submitted by: Anonymous | Date: October 10, 2024",
                    },
                    {
                        "id": 2,
                        "title": "Beyond Familiar Shores",
                        "content": "Emily's reflection on a life-changing trip abroad shows us the beauty of new cultures, connections, and the power of stepping out of our comfort zones.",
                        "date": "Submitted by: Emily W. | Date: September 15, 2024",
                    },
                    {
                        "id": 3,
                        "title": "Echoes of the Heart",
                        "date": "Submitted by: James T. | Date: August 20, 2024",
                        "content": "This powerful story of love and loss is a reminder of the impact of the people we cherish and the strength we gain from their memory.",
                    },
                ],
            },
        },
    )


def story(request, id):
    return render(
        request,
        "solidapp/story.html",
        {
            "story": {
                "title": "The Dawn Within",
                "content": "Once, in a quiet village nestled between mist-covered mountains and sprawling green meadows, there lived a young woman named Liana. From a young age, she’d felt different—always a bit out of place, as though she belonged somewhere else. Her days were filled with the routines of the village, but her heart longed for something deeper, something that pulsed with life and meaning. As the years passed, her longing grew unbearable. She couldn't ignore the nagging feeling that she was missing something important. Then, one autumn evening, when the sky was painted with strokes of amber and purple, a wanderer came through the village. With his dusty boots and road-worn cloak, he had the air of someone who’d seen far more of the world than Liana could imagine. They talked briefly, but his words left an imprint on her soul. 'Sometimes,' he said, 'you have to leave everything behind to find yourself.'",
                "date": "Submitted by: Anonymous | Date: October 10, 2024",
            }
        },
    )

solidapp/templates/solidapp/get-inspired.html
{% extends "solidapp/layout.html" %} {% load static %} {% block body %}

<main>
  <section class="hero">
    <div class="container">
      <div class="hero-inner">
        <div class="hero-copy">
          <h1 class="hero-title mt-0">{{main.title}}</h1>
          <p class="hero-paragraph">{{main.description}}</p>
        </div>
        <div class="hero-figure anime-element">
          <svg
            class="placeholder"
            width="528"
            height="396"
            viewBox="0 0 528 396"
          >
            <rect width="528" height="396" style="fill: transparent" />
          </svg>
          <div
            class="hero-figure-box hero-figure-box-01"
            data-rotation="45deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-02"
            data-rotation="-45deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-03"
            data-rotation="0deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-04"
            data-rotation="-135deg"
          ></div>
          <div class="hero-figure-box hero-figure-box-05"></div>
          <div class="hero-figure-box hero-figure-box-06"></div>
          <div class="hero-figure-box hero-figure-box-07"></div>
          <div
            class="hero-figure-box hero-figure-box-08"
            data-rotation="-22deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-09"
            data-rotation="-52deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-10"
            data-rotation="-50deg"
          ></div>
        </div>
      </div>
    </div>
  </section>
  <section class="features section">
    <div class="container">
      <div class="features-inner section-inner has-bottom-divider">
        <h4 class="feature-title text-center">{{main.section_title}}</h4>
        <p class="text-center">{{main.section_description}}</p>
        <div class="feature-wrapper">
          <h4 class="feature-title text-center">{{stories.title}}</h4>
          <div class="features-wrap">
            {% for feature in stories.data %}
            <div class="feature text-center is-revealing">
              <div class="feature-inner">
                <h4 class="feature-title mt-24">{{feature.title}}</h4>
                <p class="text-sm date">{{feature.date}}</p>
                <p class="text-md">{{feature.content}}</p>
                <a href="{% url 'solidapp:story' feature.id %}">Read More →</a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

{% endblock %}

solidapp/templates/solidapp/index.html
{% extends "solidapp/layout.html" %} {% load static %} {% block body %}
<div class="body-wrap">
  <header class="site-header">
    <div class="container">
      <div class="site-header-inner">
        <div class="brand header-brand">
          <h1 class="m-0">
            <a href="#">
              <img
                class="header-logo-image"
                src="{% static 'images/logo.svg' %}"
                alt="Logo"
              />
            </a>
          </h1>
        </div>
      </div>
    </div>
  </header>
  <main>
    <section class="hero">
      <div class="container">
        <div class="hero-inner">
          <div class="hero-copy">
            <h1 class="hero-title mt-0">{{main.title}}</h1>
            <p class="hero-paragraph">{{main.description}}</p>
            <div class="hero-cta">
              <a class="button button-primary" href="#">Inspire artists</a
              ><a class="button" href="#">Get inspired by fans</a>
            </div>
          </div>
          <div class="hero-figure anime-element">
            <svg
              class="placeholder"
              width="528"
              height="396"
              viewBox="0 0 528 396"
            >
              <rect width="528" height="396" style="fill: transparent" />
            </svg>
            <div
              class="hero-figure-box hero-figure-box-01"
              data-rotation="45deg"
            ></div>
            <div
              class="hero-figure-box hero-figure-box-02"
              data-rotation="-45deg"
            ></div>
            <div
              class="hero-figure-box hero-figure-box-03"
              data-rotation="0deg"
            ></div>
            <div
              class="hero-figure-box hero-figure-box-04"
              data-rotation="-135deg"
            ></div>
            <div class="hero-figure-box hero-figure-box-05"></div>
            <div class="hero-figure-box hero-figure-box-06"></div>
            <div class="hero-figure-box hero-figure-box-07"></div>
            <div
              class="hero-figure-box hero-figure-box-08"
              data-rotation="-22deg"
            ></div>
            <div
              class="hero-figure-box hero-figure-box-09"
              data-rotation="-52deg"
            ></div>
            <div
              class="hero-figure-box hero-figure-box-10"
              data-rotation="-50deg"
            ></div>
          </div>
        </div>
      </div>
    </section>
    <section class="features section">
      <div class="container">
        <div class="features-inner section-inner has-bottom-divider">
          <div class="features-wrap">
            {% for feature in features %}
            <div class="feature text-center is-revealing">
              <div class="feature-inner">
                <div class="feature-icon">
                  <img
                    src="{% static 'images/feature-icon-' %}{{ feature.id }}.svg"
                    alt="Feature {{ feature.id }}"
                  />
                </div>
                <h4 class="feature-title mt-24">{{feature.title}}</h4>
                <p class="text-sm mb-0">{{feature.feature}}</p>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </section>
    <section class="pricing section">
      <div class="container-sm">
        <div class="pricing-inner section-inner">
          <div class="pricing-header text-center">
            <h2 class="section-title mt-0">{{about.title}}</h2>
            <p class="section-paragraph mb-0">{{about.description}}</p>
          </div>
        </div>
      </div>
    </section>
    <section class="cta section">
      <div class="container">
        <div class="cta-inner section-inner">
          <form action="" method="post">
            {% csrf_token %} {{form}}
            <input
              type="submit"
              class="button button-primary button-wide-mobile"
              value="Subscribe"
            />
          </form>
        </div>
      </div>
    </section>
  </main>
  <footer class="site-footer">
    <div class="container">
      <div class="site-footer-inner">
        <div class="brand footer-brand">
          <a href="#">
            <img
              class="header-logo-image"
              src="{% static 'images/logo.svg' %}"
              alt="Logo"
            />
          </a>
        </div>
        <ul class="footer-links list-reset">
          <li>
            <a href="#">Contact</a>
          </li>
          <li>
            <a href="#">About us</a>
          </li>
          <li>
            <a href="#">FAQ's</a>
          </li>
          <li>
            <a href="#">Support</a>
          </li>
        </ul>
        <ul class="footer-social-links list-reset">
          <li>
            <a href="#">
              <span class="screen-reader-text">Facebook</span>
              <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M6.023 16L6 9H3V6h3V4c0-2.7 1.672-4 4.08-4 1.153 0 2.144.086 2.433.124v2.821h-1.67c-1.31 0-1.563.623-1.563 1.536V6H13l-1 3H9.28v7H6.023z"
                  fill="#0270D7"
                />
              </svg>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="screen-reader-text">Twitter</span>
              <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M16 3c-.6.3-1.2.4-1.9.5.7-.4 1.2-1 1.4-1.8-.6.4-1.3.6-2.1.8-.6-.6-1.5-1-2.4-1-1.7 0-3.2 1.5-3.2 3.3 0 .3 0 .5.1.7-2.7-.1-5.2-1.4-6.8-3.4-.3.5-.4 1-.4 1.7 0 1.1.6 2.1 1.5 2.7-.5 0-1-.2-1.5-.4C.7 7.7 1.8 9 3.3 9.3c-.3.1-.6.1-.9.1-.2 0-.4 0-.6-.1.4 1.3 1.6 2.3 3.1 2.3-1.1.9-2.5 1.4-4.1 1.4H0c1.5.9 3.2 1.5 5 1.5 6 0 9.3-5 9.3-9.3v-.4C15 4.3 15.6 3.7 16 3z"
                  fill="#0270D7"
                />
              </svg>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="screen-reader-text">Google</span>
              <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M7.9 7v2.4H12c-.2 1-1.2 3-4 3-2.4 0-4.3-2-4.3-4.4 0-2.4 2-4.4 4.3-4.4 1.4 0 2.3.6 2.8 1.1l1.9-1.8C11.5 1.7 9.9 1 8 1 4.1 1 1 4.1 1 8s3.1 7 7 7c4 0 6.7-2.8 6.7-6.8 0-.5 0-.8-.1-1.2H7.9z"
                  fill="#0270D7"
                />
              </svg>
            </a>
          </li>
        </ul>
        <div class="footer-copyright">
          &copy; 2024 Solid, All rights reserved
        </div>
      </div>
    </div>
  </footer>
</div>
{% endblock %}

solidapp/templates/solidapp/inspire.html
{% extends "solidapp/layout.html" %} {% load static %} {% block body %}

<main>
  <section class="hero">
    <div class="container">
      <div class="hero-inner">
        <div class="hero-copy">
          <h1 class="hero-title mt-0">{{main.title}}</h1>
          <p class="hero-paragraph">{{main.description}}</p>
          <div class="hero-cta">
            <a class="button button-primary" href="#story_form">Inspire</a>
          </div>
        </div>
        <div class="hero-figure anime-element">
          <svg
            class="placeholder"
            width="528"
            height="396"
            viewBox="0 0 528 396"
          >
            <rect width="528" height="396" style="fill: transparent" />
          </svg>
          <div
            class="hero-figure-box hero-figure-box-01"
            data-rotation="45deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-02"
            data-rotation="-45deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-03"
            data-rotation="0deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-04"
            data-rotation="-135deg"
          ></div>
          <div class="hero-figure-box hero-figure-box-05"></div>
          <div class="hero-figure-box hero-figure-box-06"></div>
          <div class="hero-figure-box hero-figure-box-07"></div>
          <div
            class="hero-figure-box hero-figure-box-08"
            data-rotation="-22deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-09"
            data-rotation="-52deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-10"
            data-rotation="-50deg"
          ></div>
        </div>
      </div>
    </div>
  </section>
  <section class="features section">
    <div class="container">
      <div class="features-inner section-inner has-bottom-divider">
        <h4 class="feature-title text-center">{{howItWorks.title}}</h4>
        <p class="text-center">{{howItWorks.description}}</p>
        <div class="features-wrap">
          {% for step in howItWorks.steps %}
          <div class="feature text-center is-revealing">
            <div class="feature-inner">
              <div class="feature-icon">
                <img
                  src="{% static 'images/feature-icon-' %}{{ step.id }}.svg"
                  alt="Feature {{ step.id }}"
                />
              </div>
              <h4 class="feature-title mt-24">{{step.title}}</h4>
              <p class="text-sm mb-0">{{step.feature}}</p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
  <section class="features section" id="story_form">
    <div class="container">
      <form action="" method="post" class="story-form">
        {{form}}
        <div class="submit-container">
          <input
            type="submit"
            class="button button-primary button-wide-mobile"
            value="Add"
          />
        </div>
      </form>
    </div>
  </section>
</main>

{% endblock %}

solidapp/templates/solidapp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Solid</title>
    <link
      href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,600"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <script src="https://unpkg.com/animejs@3.0.1/lib/anime.min.js"></script>
    <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
  </head>
  <body class="is-boxed has-animations">
    <div class="body-wrap">
      <header class="site-header">
        <div class="container">
          <div class="site-header-inner">
            <div class="brand header-brand">
              <h1 class="m-0">
                <a href="{% url 'solidapp:index' %}">
                  <img
                    class="header-logo-image"
                    src="{% static 'images/logo.svg' %}"
                    alt="Logo"
                  />
                </a>
              </h1>
            </div>
          </div>
        </div>
      </header>
      {% block body %} {% endblock %}
      <footer class="site-footer">
        <div class="container">
          <div class="site-footer-inner">
            <div class="brand footer-brand">
              <a href="#">
                <img
                  class="header-logo-image"
                  src="{% static 'images/logo.svg' %}"
                  alt="Logo"
                />
              </a>
            </div>
            <ul class="footer-links list-reset">
              <li>
                <a href="#">Contact</a>
              </li>
              <li>
                <a href="#">About us</a>
              </li>
              <li>
                <a href="#">FAQ's</a>
              </li>
              <li>
                <a href="#">Support</a>
              </li>
            </ul>
            <ul class="footer-social-links list-reset">
              <li>
                <a href="#">
                  <span class="screen-reader-text">Facebook</span>
                  <svg
                    width="16"
                    height="16"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M6.023 16L6 9H3V6h3V4c0-2.7 1.672-4 4.08-4 1.153 0 2.144.086 2.433.124v2.821h-1.67c-1.31 0-1.563.623-1.563 1.536V6H13l-1 3H9.28v7H6.023z"
                      fill="#0270D7"
                    />
                  </svg>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="screen-reader-text">Twitter</span>
                  <svg
                    width="16"
                    height="16"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M16 3c-.6.3-1.2.4-1.9.5.7-.4 1.2-1 1.4-1.8-.6.4-1.3.6-2.1.8-.6-.6-1.5-1-2.4-1-1.7 0-3.2 1.5-3.2 3.3 0 .3 0 .5.1.7-2.7-.1-5.2-1.4-6.8-3.4-.3.5-.4 1-.4 1.7 0 1.1.6 2.1 1.5 2.7-.5 0-1-.2-1.5-.4C.7 7.7 1.8 9 3.3 9.3c-.3.1-.6.1-.9.1-.2 0-.4 0-.6-.1.4 1.3 1.6 2.3 3.1 2.3-1.1.9-2.5 1.4-4.1 1.4H0c1.5.9 3.2 1.5 5 1.5 6 0 9.3-5 9.3-9.3v-.4C15 4.3 15.6 3.7 16 3z"
                      fill="#0270D7"
                    />
                  </svg>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="screen-reader-text">Google</span>
                  <svg
                    width="16"
                    height="16"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M7.9 7v2.4H12c-.2 1-1.2 3-4 3-2.4 0-4.3-2-4.3-4.4 0-2.4 2-4.4 4.3-4.4 1.4 0 2.3.6 2.8 1.1l1.9-1.8C11.5 1.7 9.9 1 8 1 4.1 1 1 4.1 1 8s3.1 7 7 7c4 0 6.7-2.8 6.7-6.8 0-.5 0-.8-.1-1.2H7.9z"
                      fill="#0270D7"
                    />
                  </svg>
                </a>
              </li>
            </ul>
            <div class="footer-copyright">
              &copy; 2024 Solid, All rights reserved
            </div>
          </div>
        </div>
      </footer>
    </div>

    <script src="{% static 'main.min.js' %}"></script>
  </body>
</html>

solidapp/templates/solidapp/story.html
{% extends "solidapp/layout.html" %} {% load static %} {% block body %}

<main>
  <section class="hero">
    <div class="container">
      <div class="hero-inner">
        <div class="hero-copy">
          <h1 class="hero-title mt-0">{{story.title}}</h1>
          <p class="text-sm date">{{story.date}}</p>
          <p class="hero-paragraph">{{story.content}}</p>
          <div class="hero-cta">
            <a
              class="button button-primary"
              href="{% url 'solidapp:getInspired' %}"
              >Back to stories</a
            >
          </div>
        </div>
        <div class="hero-figure anime-element">
          <svg
            class="placeholder"
            width="528"
            height="396"
            viewBox="0 0 528 396"
          >
            <rect width="528" height="396" style="fill: transparent" />
          </svg>
          <div
            class="hero-figure-box hero-figure-box-01"
            data-rotation="45deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-02"
            data-rotation="-45deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-03"
            data-rotation="0deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-04"
            data-rotation="-135deg"
          ></div>
          <div class="hero-figure-box hero-figure-box-05"></div>
          <div class="hero-figure-box hero-figure-box-06"></div>
          <div class="hero-figure-box hero-figure-box-07"></div>
          <div
            class="hero-figure-box hero-figure-box-08"
            data-rotation="-22deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-09"
            data-rotation="-52deg"
          ></div>
          <div
            class="hero-figure-box hero-figure-box-10"
            data-rotation="-50deg"
          ></div>
        </div>
      </div>
    </div>
  </section>
</main>

{% endblock %}